# Generated by Django 5.1.3 on 2024-12-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpost_server', '0002_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='quickpost_server.userprofile'),
        ),
    ]
