# Generated by Django 5.1.3 on 2024-12-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpost_server', '0003_alter_post_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.IntegerField(null=True),
        ),
    ]
