# Generated by Django 5.1.3 on 2024-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpost_server', '0004_alter_comment_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/314/354', upload_to=''),
        ),
    ]
