# Generated by Django 5.1.3 on 2024-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpost_server', '0008_alter_post_image_alter_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default='https://picsum.photos/224/341', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='media/profilePicture/default-pfp.png', upload_to='media/profilePicture'),
        ),
    ]
