# Generated by Django 5.1.3 on 2024-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpost_server', '0009_alter_post_image_alter_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default='https://picsum.photos/378/226', max_length=100),
        ),
    ]
